/**
 * Generator: converts src/lib/seed-content.json into
 *   supabase/seed-content.sql (INSERTs for site_content, services,
 *   process_steps, testimonials — idempotent, existing rows untouched)
 * Run with: node scripts/content-to-seed.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const seed = JSON.parse(readFileSync('src/lib/seed-content.json', 'utf8'));

const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
const qj = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const lists = ['services', 'process_steps', 'testimonials'];
let sql = '-- Seed data for site content (generated by scripts/content-to-seed.mjs)\n\n';

const contentKeys = Object.keys(seed).filter((k) => !lists.includes(k));
sql += 'insert into site_content (key, data)\nvalues\n';
sql += contentKeys.map((k) => `  (${q(k)}, ${qj(seed[k])})`).join(',\n');
sql += '\non conflict (key) do nothing;\n\n';

sql += 'insert into services (sort, number, title, description, icon)\nselect * from (values\n';
sql += seed.services
  .map((s) => `  (${s.sort}, ${q(s.number)}, ${q(s.title)}, ${q(s.description)}, ${q(s.icon)})`)
  .join(',\n');
sql += '\n) as v(sort, number, title, description, icon)\nwhere not exists (select 1 from services);\n\n';

sql += 'insert into process_steps (sort, title, description)\nselect * from (values\n';
sql += seed.process_steps.map((s) => `  (${s.sort}, ${q(s.title)}, ${q(s.description)})`).join(',\n');
sql += '\n) as v(sort, title, description)\nwhere not exists (select 1 from process_steps);\n\n';

sql += 'insert into testimonials (sort, quote, attribution)\nselect * from (values\n';
sql += seed.testimonials.map((t) => `  (${t.sort}, ${q(t.quote)}, ${q(t.attribution)})`).join(',\n');
sql += '\n) as v(sort, quote, attribution)\nwhere not exists (select 1 from testimonials);\n';

writeFileSync('supabase/seed-content.sql', sql);
console.log(`Wrote ${contentKeys.length} site_content keys + ${seed.services.length} services + ${seed.process_steps.length} steps + ${seed.testimonials.length} testimonials.`);
