/**
 * One-off generator: converts src/content/properties/*.md into
 *   - src/lib/seed-properties.json (bundled fallback data)
 *   - supabase/seed.sql            (INSERTs for the properties table)
 * Run with: node scripts/properties-to-seed.mjs
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import yaml from 'js-yaml';

const dir = 'src/content/properties';
const rows = [];

for (const file of readdirSync(dir).filter((f) => f.endsWith('.md')).sort()) {
  const raw = readFileSync(`${dir}/${file}`, 'utf8');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) throw new Error(`No frontmatter in ${file}`);
  const fm = yaml.load(m[1]);
  rows.push({
    slug: file.replace(/\.md$/, ''),
    name: fm.name,
    display_order: fm.order,
    status: fm.status,
    suburb: fm.suburb,
    state: fm.state ?? 'Queensland',
    year: fm.year,
    beds: fm.beds,
    baths: fm.baths,
    cars: fm.cars,
    land: fm.land,
    land_over: fm.landOver ?? false,
    image: fm.image,
    focus: fm.focus ?? '',
    headline: fm.headline,
    seo_description: fm.seoDescription,
    features: fm.features,
    gallery: fm.gallery,
    enquiry_heading: fm.enquiryHeading,
    enquiry_text: fm.enquiryText,
    enquiry_button: fm.enquiryButton ?? 'Submit Enquiry',
    description: m[2].trim(),
  });
}

rows.sort((a, b) => a.display_order - b.display_order);
writeFileSync('src/lib/seed-properties.json', JSON.stringify(rows, null, 2) + '\n');

const q = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const cols = Object.keys(rows[0]);
const values = rows.map((r) => `  (${cols.map((c) => q(r[c])).join(', ')})`).join(',\n');
mkdirSync('supabase', { recursive: true });
writeFileSync(
  'supabase/seed.sql',
  `-- Seed data for the properties table (generated by scripts/properties-to-seed.mjs)\n` +
    `insert into properties (${cols.join(', ')})\nvalues\n${values}\n` +
    `on conflict (slug) do nothing;\n`
);

console.log(`Wrote ${rows.length} properties to seed JSON and SQL.`);
